#!/bin/bash
# **************************************************************************** #
#
#                                                                              #
#                                                         :::      ::::::::    #
#    02                                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mbenhass <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/23 13:29:29 by mbenhass          #+#    #+#              #
#    Updated: 2019/10/23 13:31:11 by mbenhass         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

if [ $EUID -ne 0 ]
then
	echo "Need root access to proceed"
	exit
fi

if [ $# -eq 0 ]
then
	echo "usage : ./02 [login_to_remove]"
	exit
fi

USER=`cat /etc/passwd | cut -d ":" -f 1 | grep -x $1`

if [ -z "$USER" ]
then
	echo "Invalid login : $1 was not found."
	exit
fi

pkill -u "$USER"
deluser --force --remove-home "$USER"
